### ISSUE TITLE
demo  打不开

### ISSUE THREAD

**Issue by ulo-huangsz** [xiaoyann/foundation#1]
为什么下载下来后点击没有效果

**Comment by xiaoyann** [comment]
安装模块了吗？里面的 example 需要启动 webpack

**Comment by ulo-huangsz** [comment]
我的项目是用vue-cli 创建的 想调用你这个alert 但是一直提醒 this.Alerts is not a function 我觉得在readme里面可以加一些down下来之后需要哪些步骤让项目跑起来

**Comment by xiaoyann** [comment]
这个不是这样用的，readme 里写了呀，https://github.com/xiaoyann/foundation#alerttitle-content-buttons

**Comment by xiaoyann** [comment]
用 vue 的话，还是用这个吧，https://xiaoyann.github.io/smart-ui/docs/#/Installation
